name: Build and deploy mkdocs
on:
  push:
    branches:
      - main  # Set this to your default branch

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history for .GitInfo and .Lastmod
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs-material
          # Add any other plugins you need here
          # pip install mkdocs-some-plugin
          
      - name: Build and deploy MkDocs site
        run: |
          # Build the site
          mkdocs build
          
          # Copy questionnaires
          cp -r questionnaires/ site/questionnaires/
          
          # Deploy without rebuilding
          mkdocs gh-deploy --force --no-build
